#!/usr/bin/env python3
"""Build readable, stdlib-only Python 3.6 CamFlow standalone artifact.

Usage:
    python3 build_camflow.py
    python3 build_camflow.py --output dist/camflow

The generated artifact is a shell/Python polyglot, mirroring CamC's build
flow. Source modules must be Python 3.6 compatible and may use stdlib only.
"""
from __future__ import print_function

import argparse
import os
import re
import stat
import subprocess
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.join(ROOT, "src", "camflow_pkg")
DIST = os.path.join(ROOT, "dist")
MODULE_ORDER = ["__init__", "yaml_lite", "contracts", "engine", "cli"]


def _read(name):
    with open(os.path.join(PKG, name + ".py"), "r") as handle:
        return handle.read()


def _strip_docstring(source):
    lines = source.splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and lines[0].lstrip().startswith('\"\"\"'):
        first = lines.pop(0)
        if first.count('\"\"\"') < 2:
            while lines:
                if '\"\"\"' in lines.pop(0):
                    break
    return "\n".join(lines).lstrip("\n")


def _strip_local_imports(source):
    return "\n".join(
        line for line in source.splitlines()
        if not re.match(r"^\s*(from|import)\s+camflow_pkg", line)
        and not re.match(r"^\s*from __future__ import", line)
    )


def _embedded_skills():
    roots = [os.path.join(ROOT, "skills"), os.path.join(ROOT, "builtin", "planner", "skills")]
    found = {}
    for root in roots:
        if not os.path.isdir(root):
            continue
        for name in sorted(os.listdir(root)):
            path = os.path.join(root, name, "SKILL.md")
            if os.path.isfile(path) and name not in found:
                with open(path, "r") as handle:
                    found[name] = handle.read()
    return found


def _embedded_assets():
    """Return every checked-in builtin asset keyed by its repository path."""
    root = os.path.join(ROOT, "builtin")
    found = {}
    if not os.path.isdir(root):
        return found
    for parent, _dirs, names in os.walk(root):
        for name in sorted(names):
            path = os.path.join(parent, name)
            relative = os.path.relpath(path, ROOT).replace(os.sep, "/")
            with open(path, "r") as handle:
                found[relative] = handle.read()
    return found


def _literal_assignments(variable, values):
    """Return readable Python source that reconstructs a text mapping."""
    lines = []
    for key in sorted(values):
        value = values[key]
        lines.append("%s[%r] = _embedded_text([" % (variable, key))
        lines.extend("    %r," % item for item in value.splitlines())
        lines.append("], %r)" % value.endswith("\n"))
    return lines


def _build_stamp():
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "--short=7", "HEAD"], cwd=ROOT,
            stderr=subprocess.DEVNULL).decode("utf-8").strip()
    except Exception:
        sha = "unknown"
    return "%s %s" % (sha, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))


def build():
    stamp = _build_stamp()
    parts = [
        "#!/bin/sh",
        "''':'",
        "exec \"${CAMFLOW_PYTHON:-python3}\" \"$0\" \"$@\"",
        ":'''",
        '\"\"\"camflow — standalone Python 3.6+ workflow runner.',
        "",
        "Auto-generated by build_camflow.py. Do not edit directly.",
        "Edit src/camflow_pkg/ and rebuild.",
        '\"\"\"',
        "",
        "def _embedded_text(lines, trailing_newline):",
        "    text = \"\\n\".join(lines)",
        "    return text + (\"\\n\" if trailing_newline else \"\")",
        "",
    ]
    for name in MODULE_ORDER:
        body = _strip_local_imports(_strip_docstring(_read(name)))
        if name == "__init__":
            body = body.replace('__build__ = ""', '__build__ = "%s"' % stamp)
        parts.extend(["# " + "=" * 72, "# " + name, "# " + "=" * 72, body, ""])
    parts.extend(_literal_assignments("_EMBEDDED_SKILLS", _embedded_skills()))
    parts.extend(_literal_assignments("_EMBEDDED_ASSETS", _embedded_assets()))
    parts.extend(["", "if __name__ == \"__main__\":", "    raise SystemExit(main())", ""])
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", "-o", default=os.path.join(DIST, "camflow"))
    args = parser.parse_args()
    output = build()
    parent = os.path.dirname(os.path.abspath(args.output))
    if not os.path.isdir(parent):
        os.makedirs(parent)
    with open(args.output, "w") as handle:
        handle.write(output)
    os.chmod(args.output, os.stat(args.output).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("Built %s (%d lines, %s)" % (args.output, output.count("\n"), _build_stamp()))


if __name__ == "__main__":
    main()
