"""Hermetic E2E for examples/value-demo/workflow-reference.yaml.

What this test exercises end-to-end (no real LLM):

  1. workflow-reference.yaml parses + validates against the fixture.
  2. The runtime reaches every node in the reference DAG.
  3. The implementer's verify.command (bash scripts/run_all_tests.sh)
     fails on attempt 1 — code unchanged from the stub — so
     `retry_triggered` fires, `previous.feedback` lands on attempt 2's
     input.
  4. On attempt 2 the implementer (here, our fake) writes the real
     csvparser.py to the project; verify.command passes; downstream
     tool nodes (test_runner, invariant_checker) actually run pytest
     and observe data.passed=true.
  5. Per-attempt artifacts (output.json, prompt.txt for skill, raw
     stdout / agent_output.json for tools) are persisted at the spec'd
     paths.
  6. Workflow ends in lifecycle "done".

Skill nodes (analyzer, implementer, reviewer) and the default
agent-verify subagent are served by a single fake `camc.run_and_collect`
that disambiguates by the `name` kwarg (`-attempt-` vs `-verify-`).

Tool nodes (test_runner, invariant_checker) and the implementer's
verify.command are *real* subprocess invocations — that's the part of
the runtime worth exercising for real here.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest
import yaml


REPO = Path(__file__).resolve().parent.parent
FIXTURE = REPO / "examples" / "value-demo" / "fixture"
WF_PATH = REPO / "examples" / "value-demo" / "workflow-reference.yaml"


REAL_CSVPARSER_IMPL = '''\
"""Single-line CSV parser. Generated by E2E test fake."""
def parse_record(line: str) -> list[str]:
    fields: list[str] = []
    cur: list[str] = []
    in_quotes = False
    i = 0
    while i < len(line):
        ch = line[i]
        if in_quotes:
            if ch == '"':
                if i + 1 < len(line) and line[i + 1] == '"':
                    cur.append('"')
                    i += 2
                    continue
                in_quotes = False
                i += 1
                continue
            cur.append(ch)
            i += 1
            continue
        if ch == '"':
            in_quotes = True
            i += 1
            continue
        if ch == ',':
            fields.append(''.join(cur).strip())
            cur = []
            i += 1
            continue
        cur.append(ch)
        i += 1
    fields.append(''.join(cur).strip())
    return fields
'''


def _approve_evaluator_envelope(n_steps: int) -> dict:
    """Canned evaluator envelope of the v1.1 fixed shape."""
    return {
        "status": "success",
        "data": {
            "approved": True,
            "reasoning": "fake approval (test)",
            "step_results": [
                {"step": i + 1, "passed": True,
                 "evidence": "n/a (test fake)",
                 "reasoning": "n/a (test fake)"}
                for i in range(n_steps)
            ],
        },
        "error": None,
        "feedback": None,
        "request_human": False,
    }


def _make_fake_camc(project_root: Path):
    """Returns a fake `camc.run_and_collect` plus a call-log list."""
    calls: list[dict] = []

    def fake(*, prompt, workspace, name, tag, output_file,
             timeout_s, write_id_to=None):  # noqa: ARG001
        calls.append({"name": name, "workspace": str(workspace)})

        def _emit(envelope: dict, aid: str):
            # Mirror real camc: persist the raw agent output to the
            # workspace so per-attempt artifacts exist on disk.
            Path(workspace).mkdir(parents=True, exist_ok=True)
            (Path(workspace) / output_file).write_text(
                json.dumps(envelope, indent=2)
            )
            return (aid, envelope)

        # Branch: regular run (`-attempt-`) vs verify-agent (`-verify-`).
        if "-verify-" in name:
            # name format: "<node_id>-verify-<n>"
            node_id = name.rsplit("-verify-", 1)[0]
            n_steps_by_node = {
                "analyzer": 3,
                "reviewer": 4,
            }
            return _emit(_approve_evaluator_envelope(
                n_steps_by_node[node_id]), "verify-aid")

        # Regular skill run. name format: "<node_id>-attempt-<n>"
        node_id, _, attempt_s = name.rpartition("-attempt-")
        attempt_n = int(attempt_s)

        if node_id == "analyzer":
            return _emit({
                "status": "success",
                "data": {
                    "requirements": [
                        {"req": 1, "text": "split on ','"},
                        {"req": 2, "text": "strip whitespace"},
                        {"req": 3, "text": "quoted literal commas"},
                        {"req": 4, "text": "doubled quote inside quoted"},
                    ],
                    "test_paths_referenced": [
                        "tests/test_csvparser.py",
                        "tests/invariants/test_invariants.py",
                    ],
                },
                "error": None, "feedback": None, "request_human": False,
            }, "ana-aid")

        if node_id == "implementer":
            if attempt_n == 1:
                # Lie — claim success without writing anything. The
                # verify.command (real pytest) will catch this.
                return _emit({
                    "status": "success",
                    "data": {
                        "files_changed": ["lib/csvparser.py"],
                        "summary": "stub claim (test fake — no write)",
                    },
                    "error": None, "feedback": None, "request_human": False,
                }, "imp-aid-1")
            # Attempt 2: actually write the impl, then claim success.
            (project_root / "lib" / "csvparser.py").write_text(
                REAL_CSVPARSER_IMPL
            )
            return _emit({
                "status": "success",
                "data": {
                    "files_changed": ["lib/csvparser.py"],
                    "summary": "wrote real impl on retry",
                },
                "error": None, "feedback": None, "request_human": False,
            }, "imp-aid-2")

        if node_id == "reviewer":
            return _emit({
                "status": "success",
                "data": {"approved": True, "issues": []},
                "error": None, "feedback": None, "request_human": False,
            }, "rev-aid")

        raise AssertionError(f"unexpected fake-camc call: name={name!r}")

    return fake, calls


def _trace_events(run_dir: Path) -> list[dict]:
    p = run_dir / "trace.jsonl"
    if not p.exists():
        return []
    return [json.loads(line) for line in p.read_text().splitlines() if line]


@pytest.mark.skipif(shutil.which("jq") is None,
                    reason="workflow-reference.yaml uses jq in verify.command "
                           "for tool nodes; install jq to run this E2E.")
def test_workflow_reference_e2e(tmp_path, monkeypatch):
    from runner import runtime as rt
    from runner.runtime import run_workflow, parse_workflow_yaml

    # 1. Set up an isolated copy of the fixture.
    proj = tmp_path / "proj"
    shutil.copytree(FIXTURE, proj)
    assert (proj / "SPEC.md").is_file()
    assert (proj / "lib" / "csvparser.py").is_file()
    assert "NotImplementedError" in (proj / "lib" / "csvparser.py").read_text()

    # 2. Parse + validate workflow-reference.yaml against the project root.
    spec = parse_workflow_yaml(WF_PATH.read_text(), project_root=proj)
    assert spec["workflow"] == "csvparser_implementation"
    node_ids = [n["id"] for n in spec["nodes"]]
    assert node_ids == [
        "analyzer", "implementer", "test_runner",
        "invariant_checker", "reviewer",
    ]

    # 3. Wire fake camc.
    fake, calls = _make_fake_camc(proj)
    monkeypatch.setattr(rt.camc, "run_and_collect", fake)
    # Tame the timeout knob (irrelevant to the fake but keeps tests fast
    # if real camc were ever used).
    monkeypatch.setattr(rt.camc, "DEFAULT_SKILL_TIMEOUT_S", 30, raising=False)

    # 4. Run.
    run_dir = proj / ".camflow" / "run"
    monkeypatch.chdir(proj)
    result = run_workflow(spec, run_dir)
    assert result == "done", (
        f"expected 'done', got {result!r}; "
        f"halt={(run_dir / 'halt.json').read_text() if (run_dir / 'halt.json').exists() else 'none'}"
    )

    # 5. Implementer attempt 1 is fail (verify command saw failing pytest).
    imp1 = json.loads(
        (run_dir / "nodes" / "implementer" / "attempt-1" / "output.json").read_text()
    )
    assert imp1["status"] == "fail"
    assert "VERIFY" in (imp1.get("error") or {}).get("code", "") or \
           "VERIFY_FAIL" == imp1.get("error", {}).get("code")

    # 6. Implementer attempt 2 succeeds; csvparser.py now real.
    imp2_dir = run_dir / "nodes" / "implementer" / "attempt-2"
    imp2 = json.loads((imp2_dir / "output.json").read_text())
    assert imp2["status"] == "success"
    csvparser_now = (proj / "lib" / "csvparser.py").read_text()
    assert "NotImplementedError" not in csvparser_now
    assert "parse_record" in csvparser_now

    # 7. previous.feedback was injected on attempt 2's input.
    imp2_input = json.loads((imp2_dir / "input.json").read_text())
    assert "previous" in imp2_input
    prev_fb = (imp2_input["previous"].get("feedback")
               or imp2_input["previous"].get("error", {}).get("message", ""))
    assert prev_fb, "attempt-2 must carry previous.feedback (or error msg)"

    # 8. retry_triggered fired for the implementer.
    events = _trace_events(run_dir)
    retry_triggered = [e for e in events if e.get("event") == "retry_triggered"]
    assert any(e.get("node") == "implementer" for e in retry_triggered), (
        f"expected retry_triggered for implementer, got events: "
        f"{[e.get('event') for e in events]}"
    )

    # 9. Tool nodes ran for real and passed.
    tr = json.loads(
        (run_dir / "nodes" / "test_runner" / "attempt-1" / "output.json").read_text()
    )
    assert tr["status"] == "success"
    assert tr["data"]["passed"] is True
    assert tr["data"]["tests_run"] >= 1

    inv = json.loads(
        (run_dir / "nodes" / "invariant_checker" / "attempt-1" / "output.json").read_text()
    )
    assert inv["status"] == "success"
    assert inv["data"]["passed"] is True
    assert inv["data"]["tests_run"] >= 3
    assert inv["data"]["failed_tests"] == []

    # 10. Reviewer received upstream from all 4 prior nodes.
    rev_input = json.loads(
        (run_dir / "nodes" / "reviewer" / "attempt-1" / "input.json").read_text()
    )
    upstream_keys = set((rev_input.get("upstream") or {}).keys())
    assert upstream_keys == {"analyzer", "implementer",
                             "test_runner", "invariant_checker"}, upstream_keys

    # 11. Per-attempt persistence — pick representative paths.
    assert (run_dir / "nodes" / "analyzer" / "attempt-1" / "prompt.txt").is_file()
    assert (run_dir / "nodes" / "analyzer" / "attempt-1" /
            "agent_output.json").is_file()
    assert (run_dir / "nodes" / "implementer" / "attempt-1" /
            "agent_output.json").is_file()
    assert (run_dir / "nodes" / "test_runner" / "attempt-1" /
            "agent_output.json").is_file()
    assert (run_dir / "nodes" / "test_runner" / "attempt-1" /
            "raw_stdout.txt").is_file()

    # 12. Sanity on the call log.
    names = [c["name"] for c in calls]
    # Expect at minimum: analyzer-attempt-1, analyzer-verify-1,
    # implementer-attempt-1, implementer-attempt-2, reviewer-attempt-1,
    # reviewer-verify-1. (Implementer/tool nodes have command verifies,
    # so no -verify- calls there.)
    assert "analyzer-attempt-1" in names
    assert "analyzer-verify-1" in names
    assert "implementer-attempt-1" in names
    assert "implementer-attempt-2" in names
    assert "reviewer-attempt-1" in names
    assert "reviewer-verify-1" in names


def test_setup_fixture_script_refuses_existing(tmp_path):
    """The harness must not silently overwrite a previous A/B leg."""
    import subprocess
    setup = REPO / "examples" / "value-demo" / "scripts" / "setup-fixture.sh"
    dest = tmp_path / "x"
    p1 = subprocess.run(["bash", str(setup), str(dest)],
                        capture_output=True, text=True)
    assert p1.returncode == 0, p1.stderr
    assert dest.is_dir()
    p2 = subprocess.run(["bash", str(setup), str(dest)],
                        capture_output=True, text=True)
    assert p2.returncode != 0
    assert "already exists" in (p2.stderr + p2.stdout)


def test_score_py_on_pristine_fixture(tmp_path):
    """score.py runs end-to-end on a copy of the pristine fixture and
    emits valid rubric JSON. Pristine = no implementation, so visible
    test fails; that exercises the scoring branches."""
    import subprocess
    proj = tmp_path / "leg"
    shutil.copytree(FIXTURE, proj)
    score_py = REPO / "examples" / "value-demo" / "scripts" / "score.py"
    p = subprocess.run(
        ["python3", str(score_py), str(proj),
         "--pristine", str(FIXTURE)],
        capture_output=True, text=True,
    )
    assert p.returncode == 0, f"stderr={p.stderr}\nstdout={p.stdout}"
    out = json.loads(p.stdout)
    rubric = out["rubric"]
    # Pristine has no impl → tests fail → req coverage 0, test 0,
    # diff 0 → robust 0.
    assert rubric["test_correctness"]["auto_pts"] == 0
    assert rubric["robustness_minimality"]["auto_pts"] == 0
    # No .camflow/run → camflow.present false → audit_pts == 1,
    # recovery null (manual).
    assert out["camflow"]["present"] is False
    assert rubric["process_auditability"]["auto_pts"] == 1
    assert rubric["recovery"]["auto_pts"] is None
    # Manual rows must be left null for the human reviewer.
    assert rubric["evidence_quality"]["manual_pts"] is None


def test_workflow_reference_validates_under_repo_skills():
    """workflow-reference.yaml must validate against project_root=fixture
    using the camflow-repo's skills/ dir as fallback (analyzer,
    code_writer, reviewer must all be findable)."""
    from runner.runtime import parse_workflow_yaml
    spec = parse_workflow_yaml(WF_PATH.read_text(), project_root=FIXTURE)
    skills_used = {n["run"]["skill"]
                   for n in spec["nodes"] if "skill" in (n.get("run") or {})}
    assert skills_used == {"analyzer", "code_writer", "reviewer"}
