#!/usr/bin/env python3
"""Build a zero-install single-file CamFlow launcher.

The generated file is intentionally a small Python launcher with an embedded
tar.gz release tree. It uses only the stdlib at startup, extracts the immutable
payload into a user cache, then execs the packaged runtime with vendored deps on
PYTHONPATH. This keeps remote install to one file while preserving the normal
release tree internally.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import os
from pathlib import Path
import stat
import tarfile
import textwrap


def _read_version(release_dir: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in (release_dir / "VERSION").read_text().splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            data[k] = v
    return data


def _make_payload(release_dir: Path) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        tar.add(release_dir, arcname="camflow-release")
    return buf.getvalue()


def _launcher(version: dict[str, str], payload: bytes) -> str:
    payload_b64 = "\n".join(textwrap.wrap(base64.b64encode(payload).decode(), 76))
    payload_sha = hashlib.sha256(payload).hexdigest()
    version_s = version.get("version", "unknown")
    commit_s = version.get("commit", "unknown")
    built_at_s = version.get("built_at", "unknown")

    return f'''#!/usr/bin/env python3
"""camflow — single-file zero-install release.

Auto-generated by scripts/build_single.py. Do not edit directly.
"""

import base64
import hashlib
import io
import os
from pathlib import Path
import subprocess
import sys
import tarfile
import tempfile
import warnings

VERSION = {version_s!r}
COMMIT = {commit_s!r}
BUILT_AT = {built_at_s!r}
PAYLOAD_SHA256 = {payload_sha!r}
PAYLOAD_B64 = """{payload_b64}"""


def _version_text():
    return "camflow v%s commit=%s built_at=%s" % (VERSION, COMMIT, BUILT_AT)


def _candidate_pythons():
    forced = os.environ.get("CAMFLOW_PYTHON")
    if forced:
        yield forced
    for candidate in ("python3.12", "python3.11", "python3.10", "python3"):
        yield candidate


def _is_py310_or_newer(exe):
    try:
        return subprocess.call(
            [exe, "-c", "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        ) == 0
    except OSError:
        return False


def _select_python():
    if sys.version_info >= (3, 10):
        return sys.executable
    for candidate in _candidate_pythons():
        if _is_py310_or_newer(candidate):
            return candidate
    sys.stderr.write(
        "ERROR: CamFlow requires Python >= 3.10; set CAMFLOW_PYTHON to a suitable interpreter\\n"
    )
    raise SystemExit(1)


def _cache_root():
    explicit = os.environ.get("CAMFLOW_SINGLE_FILE_CACHE")
    if explicit:
        return Path(explicit)
    home = os.environ.get("HOME")
    if home:
        return Path(home) / ".cache" / "camflow" / "single-file"
    return Path(tempfile.gettempdir()) / "camflow-single-file"


def _safe_extract(tar, dest):
    dest_resolved = dest.resolve()
    for member in tar.getmembers():
        target = (dest / member.name).resolve()
        try:
            target.relative_to(dest_resolved)
        except ValueError:
            raise RuntimeError("unsafe payload member: %s" % member.name)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        tar.extractall(dest)


def _ensure_payload():
    root = _cache_root() / PAYLOAD_SHA256[:16]
    release_dir = root / "camflow-release"
    marker = root / ".payload.sha256"
    if marker.exists() and marker.read_text().strip() == PAYLOAD_SHA256 and release_dir.exists():
        return release_dir

    root.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="extract-", dir=str(root)))
    try:
        payload = base64.b64decode(PAYLOAD_B64.encode())
        got = hashlib.sha256(payload).hexdigest()
        if got != PAYLOAD_SHA256:
            raise RuntimeError("embedded payload checksum mismatch")
        with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as tar:
            _safe_extract(tar, tmp)
        extracted = tmp / "camflow-release"
        if release_dir.exists():
            # Immutable cache path: another process likely finished first.
            pass
        else:
            extracted.rename(release_dir)
        marker.write_text(PAYLOAD_SHA256 + "\\n")
    finally:
        try:
            for path in sorted(tmp.rglob("*"), reverse=True):
                if path.is_dir():
                    path.rmdir()
                else:
                    path.unlink()
            tmp.rmdir()
        except OSError:
            pass
    return release_dir


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    py = _select_python()
    if py != sys.executable:
        os.execvpe(py, [py, __file__] + argv, os.environ.copy())

    if argv and argv[0] in ("version", "--version"):
        print(_version_text())
        return 0

    release_dir = _ensure_payload()
    env = os.environ.copy()
    py_path = "%s:%s" % (release_dir / "vendor", release_dir / "src")
    if env.get("PYTHONPATH"):
        py_path += ":" + env["PYTHONPATH"]
    env["PYTHONPATH"] = py_path
    os.execvpe(py, [py, "-m", "runner.runtime"] + argv, env)


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    release_dir = args.release_dir.resolve()
    output = args.output.resolve()
    if not (release_dir / "VERSION").exists():
        raise SystemExit(f"missing VERSION in {release_dir}")

    payload = _make_payload(release_dir)
    version = _read_version(release_dir)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_launcher(version, payload))
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"built {output}")
    print(f"payload_sha256={hashlib.sha256(payload).hexdigest()}")
    print(f"payload_bytes={len(payload)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
